const { BaseAgent } = require('./base-agent');
const { AGENT_NAMES } = require('@erwin-os/schemas');
const { logger } = require('@erwin-os/shared/logger');

class BuilderAgent extends BaseAgent {
  constructor(params) {
    super(params, AGENT_NAMES.BUILDER);
  }

  async execute() {
    logger.info('builder', `Building document for job ${this.job.job_id}`);

    const plan = this.context.documentPlan;
    const evidencePack = this.context.evidencePack;

    if (!plan || !plan.structure?.sections) {
      throw new Error('No document plan available');
    }

    const frontMatter = this.buildFrontMatter(plan);
    const sections = [];

    for (const section of plan.structure.sections) {
      logger.debug('builder', `Writing section: ${section.title}`);

      const sectionContent = await this.chat(`
You are writing section "${section.number}. ${section.title}" of a ${plan.document_type} document.

## Document Context
- **Title:** ${plan.title}
- **Audience:** ${plan.audience?.primary} (${plan.audience?.technical_level})
- **Section Description:** ${section.description}
- **Estimated Length:** ${section.estimated_length}

## Available Evidence
${evidencePack?.summary || 'No evidence summary available'}

## Key Sources
${(evidencePack?.sources || [])
  .filter(s => s.relevance_score > 0.3)
  .slice(0, 10)
  .map(s => `- [${s.type}] ${s.query}: ${s.content?.substring(0, 300)}`)
  .join('\n')}

${this.context.verificationResult?.repairNotes
  ? `## Repair Notes from Previous Verification\n${this.context.verificationResult.repairNotes}`
  : ''}

Write this section in clean, professional technical writing style. Use markdown formatting.
- Include relevant details from the evidence
- Cite sources where appropriate using [Source: type] notation
- Be thorough but concise
- Use appropriate headings, lists, and tables where they add clarity

Write ONLY this section's content (no front matter, no other sections).
      `, { maxTokens: 4096, temperature: 0.4 });

      sections.push({
        number: section.number,
        title: section.title,
        content: sectionContent,
      });
    }

    const fullDocument = this.assembleDocument(frontMatter, sections, plan);

    const uri = await this.saveToS3('draft.md', fullDocument, 'text/markdown');

    logger.info('builder', `Document built for job ${this.job.job_id}`, {
      sections: sections.length,
      length: fullDocument.length,
    });

    return {
      draftArtifact: {
        uri,
        content: fullDocument,
        format: 'markdown',
        sections: sections.length,
        wordCount: fullDocument.split(/\s+/).length,
      },
      outputUri: uri,
      tokensUsed: this.tokensUsed,
    };
  }

  buildFrontMatter(plan) {
    const fm = plan.front_matter || {};
    return [
      '---',
      `title: "${plan.title || this.job.title}"`,
      `author: "${fm.author || 'Erwin Mothoa'}"`,
      `date: "${new Date().toISOString().split('T')[0]}"`,
      `version: "${fm.version || '1.0'}"`,
      `status: "${fm.status || 'Draft'}"`,
      `classification: "${fm.classification || 'Internal'}"`,
      `document_type: "${plan.document_type || this.job.document_type}"`,
      `job_id: "${this.job.job_id}"`,
      '---',
    ].join('\n');
  }

  assembleDocument(frontMatter, sections, plan) {
    const parts = [frontMatter, '', `# ${plan.title || this.job.title}`, ''];

    for (const section of sections) {
      parts.push(`## ${section.number}. ${section.title}`, '');
      parts.push(section.content, '');
    }

    parts.push('---', '');
    parts.push('*Document generated by Erwin OS - The eComplete AI Technical Writer*');
    parts.push(`*Generated: ${new Date().toISOString()}*`);

    return parts.join('\n');
  }
}

module.exports = { BuilderAgent };
